# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Encrypted backup for macOS dotfiles, secrets, and configs"
  homepage "https://github.com/harshpatel5940/stash"
  version "1.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harshpatel5940/stash/releases/download/v1.0.1/stash_1.0.1_darwin_amd64.tar.gz"
    sha256 "df1c7b7169e2d2d827fd38e0f6e843b99850692fc0abfb67d5d98435184ce8ae"

    def install
      bin.install "stash"
      doc.install "README.md" if File.exist?("README.md")
      doc.install "LICENSE" if File.exist?("LICENSE")
      doc.install "CONTRIBUTING.md" if File.exist?("CONTRIBUTING.md")

      generate_completions_from_executable(bin/"stash", "completion",
                                           shells: [:bash, :zsh, :fish])
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harshpatel5940/stash/releases/download/v1.0.1/stash_1.0.1_darwin_arm64.tar.gz"
    sha256 "1fa504df629e6b50b1b8930b41106821bd0656299dd71bed82799cc68a6d1c23"

    def install
      bin.install "stash"
      doc.install "README.md" if File.exist?("README.md")
      doc.install "LICENSE" if File.exist?("LICENSE")
      doc.install "CONTRIBUTING.md" if File.exist?("CONTRIBUTING.md")

      generate_completions_from_executable(bin/"stash", "completion",
                                           shells: [:bash, :zsh, :fish])
    end
  end

  test do
    assert_match "stash", shell_output("#{bin}/stash --help")
  end
end
