# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Encrypted backup for macOS dotfiles, secrets, and configs"
  homepage "https://github.com/harshpatel5940/stash"
  version "1.2.1"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/harshpatel5940/stash/releases/download/v1.2.1/stash_1.2.1_darwin_amd64.tar.gz"
    sha256 "d3f26b5c6f0dfdd6b5af8795d4fbfc99541b2d26c20b5fbf7be61a860a59eabe"

    def install
      bin.install "stash"
      doc.install "README.md" if File.exist?("README.md")
      doc.install "LICENSE" if File.exist?("LICENSE")
      doc.install "CONTRIBUTING.md" if File.exist?("CONTRIBUTING.md")

      generate_completions_from_executable(bin/"stash", "completion",
                                           shells: [:bash, :zsh, :fish])
    end
  end
  on_arm do
    url "https://github.com/harshpatel5940/stash/releases/download/v1.2.1/stash_1.2.1_darwin_arm64.tar.gz"
    sha256 "87bdcc176b2f5f24fd3c9568109a71a19e3a9177f59cf725811d58031704b095"

    def install
      bin.install "stash"
      doc.install "README.md" if File.exist?("README.md")
      doc.install "LICENSE" if File.exist?("LICENSE")
      doc.install "CONTRIBUTING.md" if File.exist?("CONTRIBUTING.md")

      generate_completions_from_executable(bin/"stash", "completion",
                                           shells: [:bash, :zsh, :fish])
    end
  end

  test do
    assert_match "stash", shell_output("#{bin}/stash --help")
  end
end
