# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Encrypted backup for macOS dotfiles, secrets, and configs"
  homepage "https://github.com/harshpatel5940/stash"
  version "1.3.0"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/harshpatel5940/stash/releases/download/v1.3.0/stash_1.3.0_darwin_amd64.tar.gz"
    sha256 "7a1e993ca8174d9f1b5c4ab11a8641ae24dbb9d91bc5c47fabac03a5064363da"

    def install
      bin.install "stash"
      doc.install "README.md" if File.exist?("README.md")
      doc.install "LICENSE" if File.exist?("LICENSE")
      doc.install "CONTRIBUTING.md" if File.exist?("CONTRIBUTING.md")

      generate_completions_from_executable(bin/"stash", "completion",
                                           shells: [:bash, :zsh, :fish])
    end
  end
  on_arm do
    url "https://github.com/harshpatel5940/stash/releases/download/v1.3.0/stash_1.3.0_darwin_arm64.tar.gz"
    sha256 "32de10b3a5da1ddb7dfb87647c578953bd984fbe9fac42a05318ba7abcb7f331"

    def install
      bin.install "stash"
      doc.install "README.md" if File.exist?("README.md")
      doc.install "LICENSE" if File.exist?("LICENSE")
      doc.install "CONTRIBUTING.md" if File.exist?("CONTRIBUTING.md")

      generate_completions_from_executable(bin/"stash", "completion",
                                           shells: [:bash, :zsh, :fish])
    end
  end

  test do
    assert_match "stash", shell_output("#{bin}/stash --help")
  end
end
