# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Encrypted backup for macOS dotfiles, secrets, and configs"
  homepage "https://github.com/harshpatel5940/stash"
  version "1.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harshpatel5940/stash/releases/download/v1.0.1/stash_1.0.1_darwin_amd64.tar.gz"
    sha256 "f4f34b9d88df553d6bc71e80f21fb4235a450772d292f1e5ef417dd42a91179e"

    def install
      bin.install "stash"
      doc.install "README.md" if File.exist?("README.md")
      doc.install "LICENSE" if File.exist?("LICENSE")
      doc.install "CONTRIBUTING.md" if File.exist?("CONTRIBUTING.md")

      generate_completions_from_executable(bin/"stash", "completion",
                                           shells: [:bash, :zsh, :fish])
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harshpatel5940/stash/releases/download/v1.0.1/stash_1.0.1_darwin_arm64.tar.gz"
    sha256 "b63d180610d9d9a0011ace300ce0652c28b20fd837c3eeaf830ff6de2f181c10"

    def install
      bin.install "stash"
      doc.install "README.md" if File.exist?("README.md")
      doc.install "LICENSE" if File.exist?("LICENSE")
      doc.install "CONTRIBUTING.md" if File.exist?("CONTRIBUTING.md")

      generate_completions_from_executable(bin/"stash", "completion",
                                           shells: [:bash, :zsh, :fish])
    end
  end

  test do
    assert_match "stash", shell_output("#{bin}/stash --help")
  end
end
